import Link from 'next/link';

export default function TermsAndConditions() {
    return (
        <div className="min-h-screen bg-background text-foreground font-sans selection:bg-gold selection:text-black">
            {/* Navigation */}
            <nav className="fixed top-0 w-full z-50 bg-background/80 backdrop-blur-md border-b border-white/5">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <Link href="/" className="flex items-center gap-2">
                            <svg className="w-8 h-8 text-gold" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                            </svg>
                            <span className="text-xl font-bold tracking-tight text-white">xGProAi</span>
                        </Link>
                    </div>
                    <div>
                        <Link href="/" className="text-sm font-medium text-gray-400 hover:text-gold transition-colors">
                            Back to Home
                        </Link>
                    </div>
                </div>
            </nav>

            <main className="pt-32 pb-24 px-4 sm:px-6 lg:px-8">
                <div className="max-w-4xl mx-auto bg-surface-card border border-border-subtle rounded-2xl p-8 md:p-12 shadow-2xl">
                    <h1 className="text-3xl md:text-4xl font-bold text-white mb-2">Terms and Conditions</h1>
                    <p className="text-gold mb-8">Last Updated: January 29, 2026</p>

                    <div className="space-y-8 text-gray-300 leading-relaxed">

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">1. Introduction</h2>
                            <p>
                                Welcome to xGProAi. These Terms and Conditions govern your use of our website and software services. By creating an account, accessing, or using xGProAi (the "Service"), you agree to be bound by these Terms and Conditions.
                            </p>
                            <p className="mt-2">
                                These Terms constitute a legally binding agreement between you and Kamakat Holdings Ltd ("Company," "we," "us"), a company registered under the laws of the Republic of Ghana.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">2. STRICT RISK DISCLOSURE (Read Carefully)</h2>
                            <p className="font-bold text-red-400 mb-2">xGProAi is NOT a Financial Advisor.</p>
                            <ol className="list-decimal pl-5 space-y-2">
                                <li><strong className="text-white">Educational Tool Only:</strong> The analysis provided by xGProAi is generated by Artificial Intelligence for informational and educational purposes only. It does not constitute financial, investment, or trading advice.</li>
                                <li><strong className="text-white">No Signal Service:</strong> We are not a "signal provider." We do not direct you to open or close trades. Any trading decision you make is solely your responsibility.</li>
                                <li><strong className="text-white">High-Risk Warning:</strong> Trading Gold (XAU/USD), Forex, and Commodities involves a high level of risk and may not be suitable for all investors. You could sustain a loss of some or all of your invested capital.</li>
                                <li><strong className="text-white">AI Limitations:</strong> You acknowledge that AI models can "hallucinate" or generate incorrect technical analysis. You should never trade based solely on xGProAi’s output without your own independent verification.</li>
                            </ol>
                            <p className="mt-4 bg-red-900/20 border border-red-500/30 p-4 rounded-lg text-sm">
                                By using this Service, you explicitly release xGProAi and its owners from liability for any financial losses you may incur.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">3. Description of Service</h2>
                            <p>xGProAi provides an AI-powered platform that analyzes user-uploaded images of financial charts.</p>
                            <ul className="list-disc pl-5 space-y-2 mt-2">
                                <li><strong className="text-white">Availability:</strong> We strive for 99.9% uptime but do not guarantee that the Service will be uninterrupted or error-free.</li>
                                <li><strong className="text-white">Modifications:</strong> We reserve the right to modify or discontinue features at any time without notice.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">4. User Accounts</h2>
                            <ol className="list-decimal pl-5 space-y-2">
                                <li><strong className="text-white">Eligibility:</strong> You must be at least 18 years old to use this Service.</li>
                                <li><strong className="text-white">Security:</strong> You are responsible for maintaining the confidentiality of your login credentials. You are responsible for all activities that occur under your account.</li>
                                <li><strong className="text-white">One User, One Account:</strong> Sharing accounts or login credentials with other traders to split subscription costs is strictly prohibited and will result in immediate banning.</li>
                            </ol>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">5. Subscriptions and Billing</h2>
                            <ol className="list-decimal pl-5 space-y-2">
                                <li><strong className="text-white">Payment Processors:</strong> Payments are processed securely via third-party providers (e.g., Paystack, Stripe). We do not store your payment information.</li>
                                <li><strong className="text-white">Recurring Billing:</strong> Subscriptions (e.g., "Gold Pro") are billed in advance on a recurring basis (monthly or annually). Your subscription will automatically renew unless cancelled at least 24 hours before the end of the current period.</li>
                                <li><strong className="text-white">Refund Policy:</strong>
                                    <ul className="list-disc pl-5 mt-1 space-y-1">
                                        <li><strong className="text-white">Free Trial:</strong> If you are on a free trial, you may cancel anytime before the trial ends to avoid charges.</li>
                                        <li><strong className="text-white">Paid Subscriptions:</strong> Due to the digital nature of the Service (instant access to AI analysis), all sales are final, and we do not offer refunds for partial months used, except where required by Ghanaian law.</li>
                                    </ul>
                                </li>
                            </ol>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">6. Acceptable Use Policy</h2>
                            <p className="mb-2">You agree NOT to:</p>
                            <ol className="list-decimal pl-5 space-y-2">
                                <li><strong className="text-white">Reverse Engineer:</strong> Attempt to decompile, disassemble, or reverse engineer the AI models or software code.</li>
                                <li><strong className="text-white">Scraping:</strong> Use automated bots or scripts to access the Service or extract data.</li>
                                <li><strong className="text-white">Illegal Content:</strong> Upload charts containing offensive, illegal, or non-trading related imagery.</li>
                            </ol>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">7. Intellectual Property</h2>
                            <ol className="list-decimal pl-5 space-y-2">
                                <li><strong className="text-white">Your Content:</strong> You retain ownership of the screenshots you upload. You grant us a non-exclusive license to process these images to provide the Service.</li>
                                <li><strong className="text-white">Our Content:</strong> The xGProAi name, logo, website design, AI prompts, and generated analysis format are the intellectual property of the Company.</li>
                            </ol>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">8. Limitation of Liability</h2>
                            <p>To the maximum extent permitted by applicable law:</p>
                            <ul className="list-disc pl-5 space-y-2 mt-2">
                                <li>In no event shall the Company, its directors, employees, or partners be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or trading capital.</li>
                                <li>Our total liability for any claim arising out of these Terms and Conditions is limited to the amount you paid us to use the Service in the three (3) months preceding the claim.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">9. Governing Law and Dispute Resolution</h2>
                            <p>These Terms and Conditions shall be governed by and construed in accordance with the laws of the Republic of Ghana.</p>
                            <ul className="list-disc pl-5 space-y-2 mt-2">
                                <li><strong className="text-white">Dispute Resolution:</strong> Any dispute arising from these Terms shall be resolved through amicable negotiation. If negotiation fails, the dispute shall be referred to arbitration in Accra, Ghana, in accordance with the Alternative Dispute Resolution Act, 2010 (Act 798).</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-xl font-bold text-white mb-4">10. Changes to Terms</h2>
                            <p>
                                We reserve the right to modify these Terms and Conditions at any time. We will notify you of significant changes via email or a dashboard notification. Continued use of the Service after changes constitutes acceptance of the new Terms.
                            </p>
                        </section>

                    </div>
                </div>
            </main>

            <footer className="bg-background border-t border-border-subtle py-8 text-center">
                <p className="text-gray-500 text-sm">© 2026 FarNorth Edsulation Pvt Ltd. All rights reserved.</p>
            </footer>
        </div>
    );
}
